"""initial schema

Revision ID: 38f4eb005110
Revises: 
Create Date: 2026-09-25 18:54:45.008169+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '38f4eb005110'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.Enum('organizer', 'manufacturer', 'integrator', 'public_spec', 'marketplace', 'review', 'case_study', 'regulation', 'team_assumption', 'user_input', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('publisher', sa.String(length=300), nullable=True),
    sa.Column('retrieved_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources')),
    sa.UniqueConstraint('code', name=op.f('uq_data_sources_code'))
    )
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_industries')),
    sa.UniqueConstraint('code', name=op.f('uq_industries_code')),
    sa.UniqueConstraint('name', name=op.f('uq_industries_name'))
    )
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manufacturers')),
    sa.UniqueConstraint('name', name=op.f('uq_manufacturers_name'))
    )
    op.create_table('solution_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['solution_types.id'], name=op.f('fk_solution_types_parent_id_solution_types'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solution_types')),
    sa.UniqueConstraint('code', name=op.f('uq_solution_types_code'))
    )
    op.create_index(op.f('ix_solution_types_parent_id'), 'solution_types', ['parent_id'], unique=False)
    op.create_table('spec_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('group', sa.Enum('technical', 'infrastructure', 'economics', 'applicability', name='specgroup', native_enum=False, length=32), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('data_type', sa.Enum('number', 'integer', 'string', 'boolean', 'enum', 'dimensions', 'range', name='valuedatatype', native_enum=False, length=32), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('is_filterable', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spec_definitions')),
    sa.UniqueConstraint('code', name=op.f('uq_spec_definitions_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', 'vendor', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_table('dataset_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('catalog', 'facility_parameters', 'normatives', 'reference_specs', name='datasetkind', native_enum=False, length=32), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('imported_by_id', sa.Uuid(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['imported_by_id'], ['users.id'], name=op.f('fk_dataset_versions_imported_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_dataset_versions_source_id_data_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_versions'))
    )
    op.create_index(op.f('ix_dataset_versions_checksum_sha256'), 'dataset_versions', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_dataset_versions_kind'), 'dataset_versions', ['kind'], unique=False)
    op.create_table('facility_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('layout_template', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], name=op.f('fk_facility_types_industry_id_industries'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facility_types')),
    sa.UniqueConstraint('code', name=op.f('uq_facility_types_code'))
    )
    op.create_index(op.f('ix_facility_types_industry_id'), 'facility_types', ['industry_id'], unique=False)
    op.create_table('normatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('facility_type_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('is_assumption', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_type_id'], ['facility_types.id'], name=op.f('fk_normatives_facility_type_id_facility_types'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_normatives_source_id_data_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_normatives')),
    sa.UniqueConstraint('code', 'facility_type_id', name=op.f('uq_normatives_code_facility_type_id'), postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_normatives_code'), 'normatives', ['code'], unique=False)
    op.create_table('parameter_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_type_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('section', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('data_type', sa.Enum('number', 'integer', 'string', 'boolean', 'enum', 'dimensions', 'range', name='valuedatatype', native_enum=False, length=32), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('default_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('min_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('allowed_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('example', sa.String(length=200), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_type_id'], ['facility_types.id'], name=op.f('fk_parameter_definitions_facility_type_id_facility_types'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_parameter_definitions_source_id_data_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parameter_definitions')),
    sa.UniqueConstraint('facility_type_id', 'code', name=op.f('uq_parameter_definitions_facility_type_id_code'))
    )
    op.create_index(op.f('ix_parameter_definitions_facility_type_id'), 'parameter_definitions', ['facility_type_id'], unique=False)
    op.create_table('processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_type_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('driver_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_type_id'], ['facility_types.id'], name=op.f('fk_processes_facility_type_id_facility_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processes')),
    sa.UniqueConstraint('facility_type_id', 'code', name=op.f('uq_processes_facility_type_id_code'))
    )
    op.create_index(op.f('ix_processes_facility_type_id'), 'processes', ['facility_type_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('solution_type_id', sa.Integer(), nullable=True),
    sa.Column('product_class', sa.Enum('brs', 'bas', 'software', name='productclass', native_enum=False, length=32), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country_of_origin', sa.String(length=100), nullable=True),
    sa.Column('readiness_status', sa.Enum('operation', 'piloting', 'rnd', name='readinessstatus', native_enum=False, length=32), nullable=True),
    sa.Column('trl', sa.SmallInteger(), nullable=True),
    sa.Column('market_potential', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('service_life_years', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.Date(), nullable=True),
    sa.Column('dataset_version_id', sa.Integer(), nullable=True),
    sa.Column('source_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], name=op.f('fk_products_dataset_version_id_dataset_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], name=op.f('fk_products_manufacturer_id_manufacturers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['solution_type_id'], ['solution_types.id'], name=op.f('fk_products_solution_type_id_solution_types'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('external_id', name=op.f('uq_products_external_id'))
    )
    op.create_index(op.f('ix_products_is_published'), 'products', ['is_published'], unique=False)
    op.create_index(op.f('ix_products_manufacturer_id'), 'products', ['manufacturer_id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_product_class'), 'products', ['product_class'], unique=False)
    op.create_index(op.f('ix_products_readiness_status'), 'products', ['readiness_status'], unique=False)
    op.create_index(op.f('ix_products_solution_type_id'), 'products', ['solution_type_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('facility_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='projectstatus', native_enum=False, length=32), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parameter_origins', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('copied_from_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['copied_from_id'], ['projects.id'], name=op.f('fk_projects_copied_from_id_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_type_id'], ['facility_types.id'], name=op.f('fk_projects_facility_type_id_facility_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_projects_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_facility_type_id'), 'projects', ['facility_type_id'], unique=False)
    op.create_index(op.f('ix_projects_is_demo'), 'projects', ['is_demo'], unique=False)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('process_solution_types',
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('solution_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], name=op.f('fk_process_solution_types_process_id_processes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solution_type_id'], ['solution_types.id'], name=op.f('fk_process_solution_types_solution_type_id_solution_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('process_id', 'solution_type_id', name=op.f('pk_process_solution_types'))
    )
    op.create_table('product_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('scenario', sa.String(length=500), nullable=True),
    sa.Column('case_description', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], name=op.f('fk_product_applications_industry_id_industries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], name=op.f('fk_product_applications_process_id_processes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_applications_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_product_applications_source_id_data_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_applications'))
    )
    op.create_index(op.f('ix_product_applications_industry_id'), 'product_applications', ['industry_id'], unique=False)
    op.create_index(op.f('ix_product_applications_product_id'), 'product_applications', ['product_id'], unique=False)
    op.create_table('product_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('acquisition_model', sa.Enum('purchase', 'lease', 'raas', name='acquisitionmodel', native_enum=False, length=32), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price_includes_vat', sa.Boolean(), nullable=False),
    sa.Column('equipment_price', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('software_price', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('implementation_price', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('annual_service_cost', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('monthly_fee', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('min_contract_months', sa.Integer(), nullable=True),
    sa.Column('terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('included_services', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_offers_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_product_offers_source_id_data_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_offers'))
    )
    op.create_index(op.f('ix_product_offers_product_id'), 'product_offers', ['product_id'], unique=False)
    op.create_table('product_processes',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], name=op.f('fk_product_processes_process_id_processes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_processes_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'process_id', name=op.f('pk_product_processes'))
    )
    op.create_table('product_sources',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_sources_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_product_sources_source_id_data_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'source_id', name=op.f('pk_product_sources'))
    )
    op.create_table('product_spec_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('spec_definition_id', sa.Integer(), nullable=False),
    sa.Column('value_numeric', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('value_numeric_max', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('retrieved_at', sa.Date(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('is_assumption', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_spec_values_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_product_spec_values_source_id_data_sources'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spec_definition_id'], ['spec_definitions.id'], name=op.f('fk_product_spec_values_spec_definition_id_spec_definitions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_spec_values')),
    sa.UniqueConstraint('product_id', 'spec_definition_id', name=op.f('uq_product_spec_values_product_id_spec_definition_id'))
    )
    op.create_index(op.f('ix_product_spec_values_product_id'), 'product_spec_values', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_spec_values_spec_definition_id'), 'product_spec_values', ['spec_definition_id'], unique=False)
    op.create_table('project_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('parameters_import', 'attachment', 'export', name='projectfilekind', native_enum=False, length=32), nullable=False),
    sa.Column('original_name', sa.String(length=300), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=200), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_files_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_project_files_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_files'))
    )
    op.create_index(op.f('ix_project_files_project_id'), 'project_files', ['project_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('baseline', 'purchase', 'raas', 'lease', 'custom', name='scenariokind', native_enum=False, length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_scenarios_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenarios'))
    )
    op.create_index(op.f('ix_scenarios_project_id'), 'scenarios', ['project_id'], unique=False)
    op.create_table('calculation_overrides',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('calculated_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('manual_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_calculation_overrides_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_calculation_overrides_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calculation_overrides'))
    )
    op.create_index(op.f('ix_calculation_overrides_scenario_id'), 'calculation_overrides', ['scenario_id'], unique=False)
    op.create_table('calculation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=True),
    sa.Column('calc_type', sa.Enum('selection', 'economics', 'simulation', name='calculationtype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', name='calculationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('catalog_dataset_version_id', sa.Integer(), nullable=True),
    sa.Column('inputs_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normatives_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['catalog_dataset_version_id'], ['dataset_versions.id'], name=op.f('fk_calculation_runs_catalog_dataset_version_id_dataset_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_calculation_runs_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_calculation_runs_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_calculation_runs_scenario_id_scenarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calculation_runs'))
    )
    op.create_index(op.f('ix_calculation_runs_project_id'), 'calculation_runs', ['project_id'], unique=False)
    op.create_table('scenario_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('quantity_calculated', sa.Integer(), nullable=True),
    sa.Column('quantity_manual', sa.Integer(), nullable=True),
    sa.Column('is_manual_selection', sa.Boolean(), nullable=False),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['product_offers.id'], name=op.f('fk_scenario_items_offer_id_product_offers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], name=op.f('fk_scenario_items_process_id_processes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_scenario_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_scenario_items_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_items'))
    )
    op.create_index(op.f('ix_scenario_items_product_id'), 'scenario_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_scenario_items_scenario_id'), 'scenario_items', ['scenario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_items_scenario_id'), table_name='scenario_items')
    op.drop_index(op.f('ix_scenario_items_product_id'), table_name='scenario_items')
    op.drop_table('scenario_items')
    op.drop_index(op.f('ix_calculation_runs_project_id'), table_name='calculation_runs')
    op.drop_table('calculation_runs')
    op.drop_index(op.f('ix_calculation_overrides_scenario_id'), table_name='calculation_overrides')
    op.drop_table('calculation_overrides')
    op.drop_index(op.f('ix_scenarios_project_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_project_files_project_id'), table_name='project_files')
    op.drop_table('project_files')
    op.drop_index(op.f('ix_product_spec_values_spec_definition_id'), table_name='product_spec_values')
    op.drop_index(op.f('ix_product_spec_values_product_id'), table_name='product_spec_values')
    op.drop_table('product_spec_values')
    op.drop_table('product_sources')
    op.drop_table('product_processes')
    op.drop_index(op.f('ix_product_offers_product_id'), table_name='product_offers')
    op.drop_table('product_offers')
    op.drop_index(op.f('ix_product_applications_product_id'), table_name='product_applications')
    op.drop_index(op.f('ix_product_applications_industry_id'), table_name='product_applications')
    op.drop_table('product_applications')
    op.drop_table('process_solution_types')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_demo'), table_name='projects')
    op.drop_index(op.f('ix_projects_facility_type_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_products_solution_type_id'), table_name='products')
    op.drop_index(op.f('ix_products_readiness_status'), table_name='products')
    op.drop_index(op.f('ix_products_product_class'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_manufacturer_id'), table_name='products')
    op.drop_index(op.f('ix_products_is_published'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_processes_facility_type_id'), table_name='processes')
    op.drop_table('processes')
    op.drop_index(op.f('ix_parameter_definitions_facility_type_id'), table_name='parameter_definitions')
    op.drop_table('parameter_definitions')
    op.drop_index(op.f('ix_normatives_code'), table_name='normatives')
    op.drop_table('normatives')
    op.drop_index(op.f('ix_facility_types_industry_id'), table_name='facility_types')
    op.drop_table('facility_types')
    op.drop_index(op.f('ix_dataset_versions_kind'), table_name='dataset_versions')
    op.drop_index(op.f('ix_dataset_versions_checksum_sha256'), table_name='dataset_versions')
    op.drop_table('dataset_versions')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('spec_definitions')
    op.drop_index(op.f('ix_solution_types_parent_id'), table_name='solution_types')
    op.drop_table('solution_types')
    op.drop_table('manufacturers')
    op.drop_table('industries')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
